# Generated by Django 5.1.2 on 2025-05-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='medicines',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
