# Generated by Django 5.2.1 on 2025-05-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_findmedicine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FindMedicine',
            new_name='MedicineDetail',
        ),
    ]
