# Generated by Django 5.1.2 on 2025-05-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_findmedicine_medicinedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
