# Generated by Django 5.1.2 on 2025-05-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_customuser_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='medicines',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
