# Generated by Django 5.1.2 on 2025-05-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customuser_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=13)),
                ('userID', models.IntegerField()),
                ('medicines', models.TextField(blank=True, default='{}')),
            ],
        ),
    ]
