# Generated by Django 5.1.2 on 2025-05-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_prescriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='doctorsNote',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
