# Generated by Django 5.1.2 on 2025-05-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_prescriptions_doctorsnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='prescribedBy',
            field=models.CharField(default='', max_length=30),
        ),
    ]
