# Generated by Django 5.1.2 on 2025-05-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_prescriptions_prescribedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiration',
            field=models.CharField(default='0000.00.00', max_length=10),
        ),
    ]
